language: objective-c
script:
  - xctool -workspace 整理.xcworkspace -scheme 整理 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace 整理.xcworkspace -scheme 整理Tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
