language: objective-c
osx_image: xcode11.5
xcode_project: MixT/MixT.xcodeproj
xcode_scheme: MixT
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone 11
podfile: MixT/Podfile

before_install:
- env
- xcodebuild -version
- xcodebuild -showsdks
- xcpretty --version
- xcrun instruments -w 'iPhone 11' || sleep 15

script:
- set -o pipefail
- xcodebuild clean build -project "$TRAVIS_XCODE_PROJECT"  -scheme "$TRAVIS_XCODE_SCHEME" | xcpretty
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "name=iPhone 11" -enableCodeCoverage YES | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
