# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MixT' do
  pod 'Masonry'
  pod 'YYModel'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'MJExtension'
  #pod 'BaiduMapKit'
  #pod 'DL_Platfrom', :path => '../../dependency/DL_Platfrom'

end
