# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '整理' do
  pod 'Masonry'
  pod 'YYModel'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'BaiduMapKit'

end
